 remote_theme: pmarsceill/just-the-docs
 title: Jeeroc's Notes
 author: Jeeroc
 color_scheme: config 
 include: ["https://github.com/Jeeroc/Jeeroc.github.io/tree/main/_posts/"]
 search_enabled: true
 permalink: /:title
 defaults:  
  -   scope: 
        path: ""
      values:
      layout: "default"
