 remote_theme: pmarsceill/just-the-docs
 title: Jeeroc's Notes
 author: Jeeroc
 color_scheme: config 
 keep_files:["_posts/*.md"]
 search_enabled: true
 permalink: /:title
 defaults:  
  -   scope: 
        path: ""
      values:
      layout: "default"
