 remote_theme: pmarsceill/just-the-docs
 title: Jeeroc的笔记
 author: Jeeroc
 color_scheme: config 
 defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
