 remote_theme: pmarsceill/just-the-docs
 title: Jeeroc's Notes
 author: Jeeroc
 color_scheme: config 
 layout: layout
 sidebar: true
 permalink: pretty
 defaults:  
  -   scope: 
        path: ""
      values:
      layout: "default"
